In [5]:
import pandas as pd
import numpy as np

In [2]:
pd.notna('dog')

True

In [3]:
pd.notna(pd.NA)

False

In [6]:
pd.notna(np.nan)

False

In [7]:
array = np.array([[1, np.nan, 3], [4, 5, np.nan]])

In [8]:
array

array([[ 1., nan,  3.],
       [ 4.,  5., nan]])

In [9]:
pd.notna(array)

array([[ True, False,  True],
       [ True,  True, False]])

In [10]:
index = pd.DatetimeIndex(["2017-07-05", "2017-07-06", None,
                         "2017-07-08"])

In [11]:
index

DatetimeIndex(['2017-07-05', '2017-07-06', 'NaT', '2017-07-08'], dtype='datetime64[ns]', freq=None)

In [12]:
pd.notna(index)

array([ True,  True, False,  True])

In [13]:
df = pd.DataFrame([['ant', 'bee', 'cat'], ['dog', None, 'fly']])

In [14]:
df

0     1    2
0  ant   bee  cat
1  dog  None  fly

In [15]:
pd.notna(df)

0      1     2
0  True   True  True
1  True  False  True

In [16]:
pd.notna(df[1])

0     True
1    False
Name: 1, dtype: bool